"""
Seed queries for small-corpus domains where the dataset has too few queries
to train a reliable domain classifier.

Used by train_classifier.py when a domain has fewer than min_queries_per_domain.
These are carefully chosen to be representative, not to overfit.
"""

SEEDS: dict[str, list[str]] = {
    "science": [
        "what is the mechanism of crispr gene editing",
        "how do black holes form and evaporate",
        "what causes superconductivity at room temperature",
        "explain the higgs boson discovery",
        "what are the implications of quantum entanglement",
        "how does mRNA vaccine technology work",
        "what is the evidence for dark matter",
        "how do neural networks learn representations",
        "what is the role of mitochondria in apoptosis",
        "explain climate feedback loops in atmospheric science",
        "how does protein folding determine function",
        "what is the significance of the james webb telescope findings",
        "how do catalysts lower activation energy",
        "what is CRISPR base editing",
        "explain the multiverse hypothesis in physics",
        "how does epigenetics affect gene expression",
        "what causes antibiotic resistance in bacteria",
        "how do gravitational waves propagate",
        "what is the difference between fusion and fission",
        "how does the immune system recognize antigens",
    ],
    "medical": [
        "what are the symptoms of type 2 diabetes",
        "clinical trial outcomes for lung cancer treatment",
        "what is the mechanism of action of statins",
        "how is sepsis diagnosed in intensive care",
        "what are the side effects of immunosuppressants",
        "covid-19 treatment protocols in hospital settings",
        "what biomarkers predict myocardial infarction risk",
        "how is alzheimer's disease diagnosed",
        "what are the criteria for ICU admission",
        "standard of care for septic shock in adults",
        "what is the prognosis for stage 3 pancreatic cancer",
        "how are ventilators managed in ARDS patients",
        "what causes autoimmune hepatitis",
        "clinical presentation of multiple sclerosis",
        "how is rheumatoid arthritis treated",
        "what is the evidence for aspirin in cardiovascular prevention",
        "how do beta blockers affect heart rate",
        "what is the role of cortisol in stress response",
        "how is chronic kidney disease staged",
        "treatment options for treatment-resistant depression",
    ],
    "scidocs": [
        "which papers cite transformer models for natural language processing",
        "find papers related to graph neural network node classification",
        "papers on attention mechanism in neural machine translation",
        "citation recommendation for deep learning in computer vision",
        "academic papers on reinforcement learning policy gradient methods",
        "find related works on variational autoencoders generative models",
        "papers citing bert for text classification tasks",
        "which papers are related to knowledge graph embedding",
        "academic literature on federated learning privacy preservation",
        "papers on contrastive learning self-supervised representation",
        "find papers citing imagenet convolutional neural network",
        "related works on recurrent neural networks sequence modelling",
        "papers on meta-learning few-shot classification",
        "academic papers on adversarial examples robustness neural networks",
        "find citations for word2vec distributed word representations",
        "papers related to multi-task learning shared representations",
        "which papers extend generative adversarial networks",
        "academic literature on neural architecture search automation",
        "papers on bayesian deep learning uncertainty estimation",
        "find related works on pre-trained language model fine-tuning",
    ],
    "biomedical": [
        "what is the role of p53 in cancer suppression",
        "how do cytokines mediate inflammatory response",
        "what is the mechanism of insulin resistance in type 2 diabetes",
        "how does the renin angiotensin system regulate blood pressure",
        "what are the molecular targets of chemotherapy drugs",
        "how does autophagy contribute to cell survival",
        "what is the pathophysiology of atherosclerosis",
        "how do T regulatory cells prevent autoimmunity",
        "what is the function of telomeres in aging",
        "how does lipid metabolism affect cardiovascular disease",
        "what causes mitochondrial dysfunction in neurodegenerative disease",
        "how are stem cells used in regenerative medicine",
        "what is the role of gut microbiome in immunity",
        "how does epigenetic methylation affect gene silencing",
        "what are the hallmarks of cancer",
        "how do kinase inhibitors work in targeted cancer therapy",
        "what is the mechanism of RNA interference",
        "how does the complement system function in innate immunity",
        "what causes oxidative stress in cells",
        "how does angiogenesis support tumor growth",
    ],
}
