"""
Seed queries for small-corpus domains where the dataset has too few queries
to train a reliable domain classifier.

Used by train_classifier.py when a domain has fewer than min_queries_per_domain.
These are carefully chosen to be representative, not to overfit.

medical and scidocs have 0 non-evaluation queries after BUG-3 fix, so their
seed sets are expanded to 80 queries each to provide sufficient training signal.
"""

SEEDS: dict[str, list[str]] = {
    "science": [
        "what is the mechanism of crispr gene editing",
        "how do black holes form and evaporate",
        "what causes superconductivity at room temperature",
        "explain the higgs boson discovery",
        "what are the implications of quantum entanglement",
        "how does mRNA vaccine technology work",
        "what is the evidence for dark matter",
        "how do neural networks learn representations",
        "what is the role of mitochondria in apoptosis",
        "explain climate feedback loops in atmospheric science",
        "how does protein folding determine function",
        "what is the significance of the james webb telescope findings",
        "how do catalysts lower activation energy",
        "what is CRISPR base editing",
        "explain the multiverse hypothesis in physics",
        "how does epigenetics affect gene expression",
        "what causes antibiotic resistance in bacteria",
        "how do gravitational waves propagate",
        "what is the difference between fusion and fission",
        "how does the immune system recognize antigens",
    ],
    "medical": [
        # Clinical diagnosis and symptoms
        "what are the symptoms of type 2 diabetes",
        "how is sepsis diagnosed in intensive care",
        "clinical presentation of multiple sclerosis",
        "what are the criteria for ICU admission",
        "how is alzheimer's disease diagnosed",
        "what is the prognosis for stage 3 pancreatic cancer",
        "signs and symptoms of pulmonary embolism",
        "how is acute kidney injury diagnosed",
        "clinical features of systemic lupus erythematosus",
        "what are the diagnostic criteria for rheumatoid arthritis",
        # Treatment and clinical trials
        "clinical trial outcomes for lung cancer treatment",
        "covid-19 treatment protocols in hospital settings",
        "how are ventilators managed in ARDS patients",
        "how is rheumatoid arthritis treated",
        "treatment options for treatment-resistant depression",
        "what is the evidence for aspirin in cardiovascular prevention",
        "standard of care for septic shock in adults",
        "first-line treatment for community-acquired pneumonia",
        "anticoagulation therapy in atrial fibrillation management",
        "what are current guidelines for hypertension treatment",
        # Pharmacology and mechanisms
        "what is the mechanism of action of statins",
        "what are the side effects of immunosuppressants",
        "how do beta blockers affect heart rate",
        "mechanism of action of ACE inhibitors in heart failure",
        "what are the pharmacokinetics of vancomycin",
        "how does insulin resistance develop in metabolic syndrome",
        "what causes drug-induced liver injury",
        "how do proton pump inhibitors work",
        "mechanism of glucocorticoid anti-inflammatory effects",
        "what is the role of cortisol in stress response",
        # Biomarkers and risk
        "what biomarkers predict myocardial infarction risk",
        "what causes autoimmune hepatitis",
        "how is chronic kidney disease staged",
        "prognosis of patients with heart failure with preserved ejection fraction",
        "risk factors for venous thromboembolism in surgical patients",
        "what is the role of troponin in cardiac injury diagnosis",
        "how is C-reactive protein used in infection diagnosis",
        "what imaging findings suggest pulmonary hypertension",
        "biomarkers for early detection of colorectal cancer",
        "what predicts ICU mortality in COVID-19 patients",
        # Pathophysiology
        "pathophysiology of sepsis-induced organ dysfunction",
        "how does heart failure cause pulmonary oedema",
        "mechanism of ischaemic stroke and reperfusion injury",
        "what causes hyperglycaemia in critical illness",
        "how does chronic inflammation lead to fibrosis",
        "pathogenesis of inflammatory bowel disease",
        "what is the role of endothelial dysfunction in hypertension",
        "how does obesity cause insulin resistance",
        "mechanisms of chemotherapy-induced cardiotoxicity",
        "what causes postoperative cognitive dysfunction in elderly",
        # Epidemiology and public health
        "what is the incidence of hospital-acquired infections",
        "prevalence of multidrug-resistant organisms in ICU",
        "outcomes of mechanical ventilation in ARDS patients",
        "mortality rates in patients with cardiogenic shock",
        "hospital readmission rates after myocardial infarction",
        "what factors predict hospital length of stay in pneumonia",
        "effectiveness of early mobilisation in ICU patients",
        "what is the impact of frailty on surgical outcomes",
        "outcomes of extracorporeal membrane oxygenation in adults",
        "what affects survival in out-of-hospital cardiac arrest",
        # Procedures and monitoring
        "how is mechanical ventilation weaning performed",
        "what are the indications for renal replacement therapy",
        "how is central venous pressure measured and interpreted",
        "monitoring parameters in septic shock resuscitation",
        "when is tracheostomy indicated in mechanically ventilated patients",
        "how is intracranial pressure managed after traumatic brain injury",
        "what are the risks of endoscopy in critically ill patients",
        "how is point-of-care ultrasound used in emergency medicine",
        "complications of arterial line insertion and monitoring",
        "what is the role of echocardiography in ICU management",
        # Infectious disease
        "antimicrobial stewardship in hospital-acquired infections",
        "what are risk factors for Clostridioides difficile infection",
        "management of ventilator-associated pneumonia",
        "what empirical antibiotics are used for severe sepsis",
        "efficacy of antifungal prophylaxis in immunocompromised patients",
        "how is invasive candidiasis diagnosed and treated",
        "what is the clinical significance of bacteraemia",
        "management of COVID-19 in immunosuppressed patients",
        "outcomes of SARS-CoV-2 infection in solid organ transplant recipients",
        "what is the role of corticosteroids in COVID-19 treatment",
        # COVID-19 specific (TREC-COVID test query distribution)
        "what is the origin of COVID-19",
        "how does the coronavirus respond to changes in the weather",
        "will SARS-CoV-2 infected people develop immunity",
        "what causes death from COVID-19",
        "what drugs have been active against SARS-CoV-2 in animal studies",
        "what types of rapid testing for COVID-19 have been developed",
        "are there serological tests that detect antibodies to coronavirus",
        "how has lack of testing led to underreporting of COVID-19 incidence",
        "what is the effectiveness of remdesivir against COVID-19",
        "is hydroxychloroquine effective for COVID-19 treatment",
        "what is the basic reproduction number of SARS-CoV-2",
        "how does SARS-CoV-2 enter human cells via ACE2 receptor",
        "what is the role of cytokine storm in severe COVID-19",
        "what mutations of SARS-CoV-2 have been identified",
        "how effective are mRNA vaccines against COVID-19 variants",
        "what is the duration of immunity after COVID-19 infection",
        "how does long COVID present clinically",
        "what is the case fatality rate of COVID-19 by age group",
        "how is COVID-19 transmitted between humans",
        "what is the incubation period of SARS-CoV-2",
        "what comorbidities increase COVID-19 mortality risk",
        "how effective are face masks in preventing COVID-19 transmission",
        "what is the role of children in COVID-19 transmission",
        "what are the neurological complications of COVID-19",
        "how does SARS-CoV-2 affect the cardiovascular system",
        "what diagnostic tests are used to detect COVID-19",
        "what is the survival rate of COVID-19 patients on mechanical ventilation",
        "how does the spike protein of SARS-CoV-2 bind to host cells",
        "what is the genomic structure of SARS-CoV-2",
        "what convalescent plasma therapies have been tried for COVID-19",
    ],
    "scidocs": [
        # Citation and recommendation
        "which papers cite transformer models for natural language processing",
        "find papers related to graph neural network node classification",
        "papers on attention mechanism in neural machine translation",
        "citation recommendation for deep learning in computer vision",
        "academic papers on reinforcement learning policy gradient methods",
        "find related works on variational autoencoders generative models",
        "papers citing bert for text classification tasks",
        "which papers are related to knowledge graph embedding",
        "academic literature on federated learning privacy preservation",
        "papers on contrastive learning self-supervised representation",
        "find papers citing imagenet convolutional neural network",
        "related works on recurrent neural networks sequence modelling",
        "papers on meta-learning few-shot classification",
        "academic papers on adversarial examples robustness neural networks",
        "find citations for word2vec distributed word representations",
        "papers related to multi-task learning shared representations",
        "which papers extend generative adversarial networks",
        "academic literature on neural architecture search automation",
        "papers on bayesian deep learning uncertainty estimation",
        "find related works on pre-trained language model fine-tuning",
        # NLP and language models
        "papers citing attention is all you need transformer architecture",
        "academic literature on named entity recognition sequence labelling",
        "find papers on question answering reading comprehension datasets",
        "citation network for sentiment analysis opinion mining papers",
        "papers on machine translation neural sequence to sequence models",
        "academic works related to coreference resolution in NLP",
        "papers extending BERT for domain-specific fine-tuning",
        "find related works on dependency parsing neural models",
        "papers on dialogue systems and conversational AI",
        "academic literature on summarisation abstractive extractive methods",
        # Computer vision
        "papers citing ResNet deep residual learning for image recognition",
        "find related papers on object detection YOLO faster RCNN",
        "academic literature on semantic segmentation fully convolutional",
        "citation network for generative image synthesis",
        "papers on point cloud 3D object detection neural networks",
        "related works on image captioning visual question answering",
        "papers extending vision transformers for image recognition",
        "find academic papers on video understanding temporal models",
        "works citing GAN training stability spectral normalisation",
        "papers on self-supervised visual representation learning",
        # Graphs and structured data
        "papers on graph convolutional networks semi-supervised classification",
        "academic literature on link prediction knowledge graphs",
        "find papers on community detection graph clustering methods",
        "citation network for network embedding node2vec DeepWalk",
        "papers on heterogeneous information network mining",
        "related works on dynamic graph neural networks temporal",
        "academic papers on hypergraph learning higher-order interactions",
        "find papers citing attention-based graph neural networks",
        "works on graph transformers long-range dependencies",
        "papers on molecular property prediction graph networks",
        # Recommender systems and information retrieval
        "papers on collaborative filtering matrix factorisation",
        "academic literature on session-based recommendation systems",
        "find papers on neural information retrieval dense retrieval",
        "citation network for learning to rank information retrieval",
        "papers on knowledge-aware recommendation systems",
        "related works on cross-domain recommendation transfer learning",
        "academic papers on query expansion pseudo relevance feedback",
        "find works on dense passage retrieval bi-encoder models",
        "papers on conversation search clarifying questions",
        "academic literature on entity linking knowledge base population",
        # Reinforcement learning and robotics
        "papers on model-based reinforcement learning world models",
        "academic works on multi-agent reinforcement learning cooperation",
        "find papers citing proximal policy optimisation PPO",
        "citation network for robot learning from demonstration",
        "papers on offline reinforcement learning batch constrained",
        "related works on hierarchical reinforcement learning options",
        "academic literature on exploration in sparse reward environments",
        "find papers on sim-to-real transfer for robotic manipulation",
        "works citing deep Q-network Atari game playing",
        "papers on reward shaping and curriculum learning",
        # Systems and efficiency
        "papers on efficient transformer attention mechanisms linear",
        "academic literature on neural network pruning compression",
        "find papers on knowledge distillation model compression",
        "citation network for quantisation aware training inference",
        "papers on mixture of experts sparse conditional computation",
        "related works on continual learning catastrophic forgetting",
        "academic papers on neural architecture search differentiable",
        "find papers on low-rank adaptation fine-tuning large models",
        "works on parameter efficient fine-tuning adapter modules",
        "papers on in-context learning few-shot prompting large language models",
    ],
    "biomedical": [
        "what is the role of p53 in cancer suppression",
        "how do cytokines mediate inflammatory response",
        "what is the mechanism of insulin resistance in type 2 diabetes",
        "how does the renin angiotensin system regulate blood pressure",
        "what are the molecular targets of chemotherapy drugs",
        "how does autophagy contribute to cell survival",
        "what is the pathophysiology of atherosclerosis",
        "how do T regulatory cells prevent autoimmunity",
        "what is the function of telomeres in aging",
        "how does lipid metabolism affect cardiovascular disease",
        "what causes mitochondrial dysfunction in neurodegenerative disease",
        "how are stem cells used in regenerative medicine",
        "what is the role of gut microbiome in immunity",
        "how does epigenetic methylation affect gene silencing",
        "what are the hallmarks of cancer",
        "how do kinase inhibitors work in targeted cancer therapy",
        "what is the mechanism of RNA interference",
        "how does the complement system function in innate immunity",
        "what causes oxidative stress in cells",
        "how does angiogenesis support tumor growth",
    ],
}
